export const dummyData = [
  {
    alias: "wright-and-company-detroit-3",
    categories: [
      { alias: "gastropubs", title: "Gastropubs" },
      { alias: "newamerican", title: "American (New)" },
      { alias: "tapasmallplates", title: "Tapas/Small Plates" },
    ],
    coordinates: { latitude: 42.33523, longitude: -83.04902 },
    display_phone: "(313) 962-7711",
    distance: 4581.706148846994,
    id: "7ArIKwojlm_Yca29HnGDfQ",
    image_url:
      "https://img.freepik.com/premium-vector/book-store-logo-template_6543-230.jpg",
    is_closed: false,
    location: {
      address1: "1500 Woodward Ave",
      address2: "",
      address3: "",
      city: "Detroit",
      country: "US",
      display_address: ["1500 Woodward Ave", "Detroit, MI 48226"],
      state: "MI",
      zip_code: "48226",
    },
    name: "Book Store",
    phone: "+13139627711",
    price: "$$$",
    rating: 4.5,
    review_count: 973,
    transactions: ["delivery", "pickup"],
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUDrvPrjYjb6hTp7WBIYWQal5LXK9CUjV3bA&usqp=CAU",
  },
  {
    alias: "wright-and-company-detroit-3",
    categories: [
      { alias: "gastropubs", title: "Gastropubs" },
      { alias: "newamerican", title: "American (New)" },
      { alias: "tapasmallplates", title: "Tapas/Small Plates" },
    ],
    coordinates: { latitude: 42.33523, longitude: -83.04902 },
    display_phone: "(313) 962-7711",
    distance: 4581.706148846994,
    id: "7ArIKwojlm_Yca29HnGDfQ",
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpYAXVlNVjRbhrnOIY9HBZ3kulbtS51bKxRKGWaFuRmBMCIniFv2a6bzZb09YAHi1ig0A&usqp=CAU",
    is_closed: false,
    location: {
      address1: "1500 Woodward Ave",
      address2: "",
      address3: "",
      city: "Detroit",
      country: "US",
      display_address: ["1500 Woodward Ave", "Detroit, MI 48226"],
      state: "MI",
      zip_code: "48226",
    },
    name: "Manchester's state",
    phone: "+13139627711",
    price: "$$$",
    rating: 4.5,
    review_count: 973,
    transactions: ["delivery", "pickup"],
    url: "https://www.yelp.com/biz/wright-and-company-detroit-3?adjust_creative=XSYpa0zmDuI58B8meI0c0w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=XSYpa0zmDuI58B8meI0c0w",
  },
  {
    alias: "wright-and-company-detroit-3",
    categories: [
      { alias: "gastropubs", title: "Gastropubs" },
      { alias: "newamerican", title: "American (New)" },
      { alias: "tapasmallplates", title: "Tapas/Small Plates" },
    ],
    coordinates: { latitude: 42.33523, longitude: -83.04902 },
    display_phone: "(313) 962-7711",
    distance: 4581.706148846994,
    id: "7ArIKwojlm_Yca29HnGDfQ",
    image_url:
      "https://d2p7wwv96gt4xt.cloudfront.net/S/static/strand-logo-exact.png",
    is_closed: false,
    location: {
      address1: "1500 Woodward Ave",
      address2: "",
      address3: "",
      city: "Detroit",
      country: "US",
      display_address: ["1500 Woodward Ave", "Detroit, MI 48226"],
      state: "MI",
      zip_code: "48226",
    },
    name: "Strand chain of books",
    phone: "+13139627711",
    price: "$$$",
    rating: 4.5,
    review_count: 973,
    transactions: ["delivery", "pickup"],
    url: "https://www.yelp.com/biz/wright-and-company-detroit-3?adjust_creative=XSYpa0zmDuI58B8meI0c0w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=XSYpa0zmDuI58B8meI0c0w",
  },
  {
    alias: "wright-and-company-detroit-3",
    categories: [
      { alias: "gastropubs", title: "Gastropubs" },
      { alias: "newamerican", title: "American (New)" },
      { alias: "tapasmallplates", title: "Tapas/Small Plates" },
    ],
    coordinates: { latitude: 42.33523, longitude: -83.04902 },
    display_phone: "(313) 962-7711",
    distance: 4581.706148846994,
    id: "7ArIKwojlm_Yca29HnGDfQ",
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbFdYvVOerFb7-uUE2DcjznanlRVKqSoGRHg&usqp=CAU",
    is_closed: false,
    location: {
      address1: "1500 Woodward Ave",
      address2: "",
      address3: "",
      city: "Detroit",
      country: "US",
      display_address: ["1500 Woodward Ave", "Detroit, MI 48226"],
      state: "MI",
      zip_code: "48226",
    },
    name: "The ancient bookstore",
    phone: "+13139627711",
    price: "$$$",
    rating: 4.5,
    review_count: 973,
    transactions: ["delivery", "pickup"],
    url: "https://www.yelp.com/biz/wright-and-company-detroit-3?adjust_creative=XSYpa0zmDuI58B8meI0c0w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=XSYpa0zmDuI58B8meI0c0w",
  },
];
